### PR TITLE
Fix import refs

### PR DESCRIPTION
**Pull request by drc38**

### CODE REVIEW

**Review by hardbyte — APPROVED** [review]
Cheers!

**Comment by sydney2711** [comment]
Hello. I updated core to 11.1 and evenx integration to 0.4. Unfortunately I couldn't control the max current (major reason I am using the integration). So I used my backup and went back to 10.5 and 0.31 but now the system that worked nicely before is now non functional as well.
Is there anything I can do?

Cheers

**Comment by drc38** [comment]
Just published new release, it should fix the issue above

**Comment by T1nn13** [comment]
Can confirm that controls work on Core 11.1 and integration V0.4.1
image

Thanks so much

**Comment by sydney2711** [comment]
Thank you so much for your help. Amazing how helpful the community and you
in particular are.

**Pull request merged**
