### PR TITLE
Fix attribute errors

### LINKED ISSUE #36: Evnex charger not available in 2024.6
Hello

2024.5.5 and the charger was working fine
2024.6 and I get this error log:

This error originated from a custom integration.

###############
Logger: custom_components.evnex
Source: custom_components/evnex/__init__.py:185
integration: Evnex EV Charger (documentation, issues)
First occurred: 09:53:27 (5 occurrences)
Last logged: 09:54:40

Unhandled exception while updating evnex info
Traceback (most recent call last):
  File "/config/custom_components/evnex/__init__.py", line 185, in async_update_data
    for connector_brief in charge_point_detail.connectors:
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'connectors'

#################

I hope there is a way to fix this issue because the charger is one of my most important device in home assistant.

### PR DESCRIPTION
**Pull request by drc38**
@hardbyte, something appears to have changed meaning the dot notation doesn't work for dicts in recent versions of HA. Fixes #36

### CODE REVIEW

**Comment by hardbyte** [comment]
I don't think this fix should be required, perhaps it was with an older version of python-evnex? 

I just tried with the latest homeassistant docker image and `main` worked for me.

**Comment by drc38** [comment]
> I don't think this fix should be required, perhaps it was with an older version of python-evnex?
> 
> I just tried with the latest homeassistant docker image and `main` worked for me.

I can't use evnex >=0.4 due to a pip dependency conflict. My HA pydantic is still on 1.10.15 in docker HA 2024.6.2 and I'm getting still getting the attribute error. Is it likely the two are related?

**Comment by drc38** [comment]
@hardbyte, looks like it is pydantic version related as forcing pydantic version to be >=2 gets rid of attribute error. Only problem is a number of other integrations are not yet supporting V2...

**Comment by hardbyte** [comment]
Yeah its not an ideal situation at all. If you like you could branch off the last working 0.4.x version and create a new release that targets the older pydantic.

**Comment by drc38** [comment]
Thanks, my HA install is now sorted. Hopefully the HA devs migrate to v2 soon.

**Comment by sydney2711** [comment]
Yes the charger is back online BUT I no longer can control the maximum current. I use this to charge the battery at the lowest possible amps.
Therefore this solution isn't for me.
I am going back to 2024.5

**Comment by zlodag** [comment]
> Thanks, my HA install is now sorted. Hopefully the HA devs migrate to v2 soon.

@sydney2711 @drc38  Interim fix: https://github.com/hardbyte/ha-evnex/issues/36#issuecomment-2544656736

**Pull request closed without merging**
